const DIRECTORIES = [
  { name: "Product Hunt", url: "https://www.producthunt.com", listingTemplate: "https://www.producthunt.com/posts/{slug}" },
  { name: "BetaList", url: "https://betalist.com", listingTemplate: "https://betalist.com/startups/{slug}" },
  { name: "Indie Hackers", url: "https://www.indiehackers.com", listingTemplate: "https://www.indiehackers.com/product/{slug}" },
  { name: "Hacker News", url: "https://news.ycombinator.com", listingTemplate: "https://news.ycombinator.com/item?id={id}" },
  { name: "AlternativeTo", url: "https://alternativeto.net", listingTemplate: "https://alternativeto.net/software/{slug}" },
  { name: "AppSumo", url: "https://appsumo.com", listingTemplate: "https://appsumo.com/products/{slug}" },
  { name: "Slant", url: "https://www.slant.co", listingTemplate: "https://www.slant.co/topics/{id}" },
  { name: "Crunchbase", url: "https://www.crunchbase.com", listingTemplate: "https://www.crunchbase.com/organization/{slug}" },
  { name: "Startup Base", url: "https://startupbase.io", listingTemplate: "https://startupbase.io/startup/{slug}" },
  { name: "SaaS Hub", url: "https://www.saashub.com", listingTemplate: "https://www.saashub.com/{slug}" },
  { name: "Softpedia", url: "https://www.softpedia.com", listingTemplate: "https://www.softpedia.com/get/{slug}" },
  { name: "PitchWall", url: "https://pitchwall.co", listingTemplate: "https://pitchwall.co/product/{slug}" },
  { name: "Kern.al", url: "https://kern.al", listingTemplate: "https://kern.al/idea/{slug}" },
  { name: "KillerStartups", url: "https://www.killerstartups.com", listingTemplate: "https://www.killerstartups.com/startup/{slug}" },
  { name: "StackShare", url: "https://stackshare.io", listingTemplate: "https://stackshare.io/{slug}" },
  { name: "GetApp", url: "https://www.getapp.com", listingTemplate: "https://www.getapp.com/software/{id}" },
  { name: "G2", url: "https://www.g2.com", listingTemplate: "https://www.g2.com/products/{slug}/reviews" },
  { name: "Capterra", url: "https://www.capterra.com", listingTemplate: "https://www.capterra.com/p/{id}" },
  { name: "Trustpilot", url: "https://www.trustpilot.com", listingTemplate: "https://www.trustpilot.com/review/{slug}" },
  { name: "Starter Story", url: "https://www.starterstory.com", listingTemplate: "https://www.starterstory.com/stories/{slug}" },
  { name: "Failory", url: "https://www.failory.com", listingTemplate: "https://www.failory.com/blog/{slug}" },
  { name: "Remote Tools", url: "https://www.remote.tools", listingTemplate: "https://www.remote.tools/product/{slug}" },
  { name: "SideProjectors", url: "https://www.sideprojectors.com", listingTemplate: "https://www.sideprojectors.com/project/{slug}" },
  { name: "Launching Next", url: "https://www.launchingnext.com", listingTemplate: "https://www.launchingnext.com/s/{slug}" },
  { name: "Unearthed", url: "https://unearthed.co", listingTemplate: "https://unearthed.co/startups/{slug}" },
  { name: "AppVita", url: "https://appvita.com", listingTemplate: "https://appvita.com/{slug}" },
  { name: "All Startups Info", url: "https://allstartups.info", listingTemplate: "https://allstartups.info/startup/{slug}" },
  { name: "Startup Inspire", url: "https://startupinspire.com", listingTemplate: "https://startupinspire.com/startup/{slug}" },
  { name: "Submit Startups", url: "https://submitstartups.com", listingTemplate: "https://submitstartups.com/listings/{slug}" },
  { name: "Tools Directory", url: "https://toolsdirectory.com", listingTemplate: "https://toolsdirectory.com/tool/{slug}" },
  { name: "SaaS Worthy", url: "https://www.saasworthy.com", listingTemplate: "https://www.saasworthy.com/product/{slug}" },
  { name: "Startup Ranking", url: "https://www.startupranking.com", listingTemplate: "https://www.startupranking.com/{slug}" },
  { name: "Betabound", url: "https://betabound.com", listingTemplate: "https://betabound.com/listings/{slug}" },
  { name: "10words", url: "https://10words.io", listingTemplate: "https://10words.io/product/{slug}" },
  { name: "Startup Lister", url: "https://startuplister.com", listingTemplate: "https://startuplister.com/startups/{slug}" },
  { name: "Startup Buffer", url: "https://startupbuffer.com", listingTemplate: "https://startupbuffer.com/startup/{slug}" },
  { name: "Bootstrappers", url: "https://bootstrappers.co", listingTemplate: "https://bootstrappers.co/story/{slug}" },
  { name: "Land Book", url: "https://land-book.com", listingTemplate: "https://land-book.com/websites/{slug}" },
  { name: "SaaS Club", url: "https://saasclub.io", listingTemplate: "https://saasclub.io/directory/{slug}" },
  { name: "Top SaaS", url: "https://topsaas.com", listingTemplate: "https://topsaas.com/product/{slug}" },
  { name: "Devpost", url: "https://devpost.com", listingTemplate: "https://devpost.com/software/{slug}" },
  { name: "Makerpad", url: "https://www.makerpad.co", listingTemplate: "https://www.makerpad.co/tools/{slug}" },
  { name: "NoCode Founders", url: "https://nocodefounders.com", listingTemplate: "https://nocodefounders.com/tools/{slug}" },
  { name: "Tiny Startups", url: "https://tinystartups.co", listingTemplate: "https://tinystartups.co/startup/{slug}" },
  { name: "SaaS Genius", url: "https://www.saasgenius.com", listingTemplate: "https://www.saasgenius.com/program/{slug}" },
  { name: "Crozdesk", url: "https://crozdesk.com", listingTemplate: "https://crozdesk.com/software/{slug}" },
  { name: "Startup Stash", url: "https://startupstash.com", listingTemplate: "https://startupstash.com/listing/{slug}" },
  { name: "Launching.io", url: "https://launching.io", listingTemplate: "https://launching.io/startup/{slug}" },
  { name: "Insanely Useful Websites", url: "https://insanelyusefulwebsites.com", listingTemplate: "https://insanelyusefulwebsites.com/site/{slug}" },
  { name: "Futurepedia", url: "https://www.futurepedia.io", listingTemplate: "https://www.futurepedia.io/tool/{slug}" },
  { name: "TheresAnAIForThat", url: "https://theresanaiforthat.com", listingTemplate: "https://theresanaiforthat.com/ai/{slug}" },
  { name: "Ben's Bites", url: "https://www.bensbites.co", listingTemplate: "https://www.bensbites.co/tools/{slug}" },
  { name: "AI Tool Hunt", url: "https://www.aitoolhunt.com", listingTemplate: "https://www.aitoolhunt.com/tool/{slug}" },
  { name: "TopAI.tools", url: "https://topai.tools", listingTemplate: "https://topai.tools/tool/{slug}" }
];

module.exports = { DIRECTORIES };
